
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 102400

spring:
  application:
    name: system-manager
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://103.137.98.231:1433;DatabaseName=JavaSystemManager
    username: sa
    password: adminTQz2tNbj
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1200000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存   是否要打开页面缓存？
    cache: false
    # 设置ftl文件路径
    template-loader-path: classpath:templates
    request-context-attribute: request
    settings:
      #格式化数值输出逗号问题
      number_format: 0.##
  resources:
    static-locations: classpath:/static/**,classpath:/pub/**
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  redis:
    database: 0
   # host: 103.137.98.234
    host: 103.137.98.234
    port: 6379
    password: 123123
    timeout: 10000
    jedis:
      pool:
        min-idle: 5
        max-idle: 200
        max-active: 1024
        max-wait: 100
        max-total: 20
        timeBetweenEvictionRunsMillis: 1000
        numTestsPerEvictionRun: 5
  aop:
    auto: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
#      enabled: false
  messages:
    basename: pps/config


mybatis:
  mapper-locations: classpath:**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



#pagehelper:
#  helper-dialect: sqlserver2012




shiro:
  anno: /,/login,/mylogin,/authority/shiroLogin,/authority/loginResp,/authority/ssoLogin,/authority/ssoLoginUrl,/authority/ssoLoginResp,/redirect,/static/**,/api/**,/img/**
  logout: /authority/logout,/system/logout
  authc: /index,/audit/index/**,/**

